### ISSUE TITLE
1.7.5 fails to install with pip

### ISSUE THREAD

**Issue by knewter** [okeuday/erlang_py#4]
I can't install 1.7.5 with pip as `README.markdown` isn't in the package itself, and `setup.py` tries to read from it.

```
jadams ~/p/v/a/a/agencyrocket *feature/pdf_csv λ pip3 install erlang_py                                                                                         6m 51s 238ms
Collecting erlang_py
  Downloading https://files.pythonhosted.org/packages/88/9e/3205c7345862a08809e132dd206841b70f26e74be4f5ea37373724007086/erlang_py-1.7.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vs/2zdf51mj26569h1yym12h6lh0000gn/T/pip-install-mwmxx_vi/erlang-py/setup.py", line 19, in <module>
        long_description = open('README.markdown', 'r').read()
    FileNotFoundError: [Errno 2] No such file or directory: 'README.markdown'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vs/2zdf51mj26569h1yym12h6lh0000gn/T/pip-install-mwmxx_vi/erlang-py/
```

Here are the contents of the package:

```
jadams ~/D/erlang_py-1.7.5 λ tree
.
├── PKG-INFO
├── erlang.py
├── erlang_py.egg-info
│   ├── PKG-INFO
│   ├── SOURCES.txt
│   ├── dependency_links.txt
│   └── top_level.txt
├── setup.cfg
└── setup.py

1 directory, 8 files
```

**Comment by okeuday** [comment]
@knewter If you use the most recent version, it should work as expected:

    pip install --no-cache erlang_py==1.7.7
